### ISSUE TITLE
Init SDK error

### ISSUE THREAD

**Issue by vincent-caraccio** [perpetual-protocol/perp-sdk#46]
Hello,

I'm facing the following issue:

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

contract_read_error: Read Multicall2 contract error, invoke tryAggregate function failed.
    at /home/vince/Repos/test/node_modules/@perp/v2-sdk/dist/index.js:36282:24
    at errorGuardAsync (/home/vince/Repos/test/node_modules/@perp/v2-sdk/dist/index.js:15927:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.create (/home/vince/Repos/test/node_modules/@perp/v2-sdk/dist/index.js:35778:111)
    at async PerpetualProtocol.init (/home/vince/Repos/test/node_modules/@perp/v2-sdk/dist/index.js:37947:41)
    at async file:///home/vince/Repos/test/index.js:8:3 {
  name: 'init_sdk_error',
  message: 'Init SDK error.'
}
```

I'm simply running the following:

```
import { PerpetualProtocol, SupportedChainId } from '@perp/v2-sdk';

(async function () {
  const perp = new PerpetualProtocol({
    chainId: SupportedChainId.OPTIMISTIC_ETHEREUM,
    providerConfigs: [{ rpcUrl: 'https://mainnet.optimism.io' }]
  });
  await perp.init();
})()
```

Thanks,
Vincent

**Comment by vincent-caraccio** [comment]
I works now.
